const projects = [
  {
    id: 'adidas',
    title: 'adidas',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2017, 2018',
    mentions: 'Isobar Commerce',
    link: 'https://adidas.co.uk/',
    photos: [],
  },
  {
    id: 'the-times',
    title: 'The Times & The Sunday Times',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2019',
    mentions: 'NewsUK',
    link: 'https://www.thetimes.co.uk/',
    photos: [],
  },
  {
    id: 'cmg',
    title: 'Crypto Management Group',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2021',
    mentions: '',
    link: 'https://cryptomanagement.group/',
    photos: [],
  },
  {
    id: 'danuki-dojo',
    title: 'Danuki Dojo',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2021',
    mentions: '',
    link: null,
    photos: [],
  },
  {
    id: 'newskit',
    title: 'NewsKit',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2019, 2020, 2021',
    mentions: 'NewsUK',
    link: 'https://www.newskit.co.uk/',
    photos: [],
  },
  {
    id: 'tourist-guide-in-florence',
    title: 'Tourist Guide in Florence',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2021',
    mentions: '',
    link: 'https://tourist-guide-in-florence.vercel.app/',
    photos: [],
  },
  {
    id: 'wzrds',
    title: 'WZRDS NFT',
    description: 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum',
    myWork: 'Lorem ipsum',
    times: '2021',
    mentions: '',
    link: 'https://wizardsacc.z19.web.core.windows.net/',
    photos: [],
  },
]

export default projects